export const tags = [
  "all",
  "pop",
  "news",
  "music",
  "rock",
  "classical",
  "talk",
  "radio",
  "estación",
  "méxico",
  "public radio",
  "fm",
  "música",
  "christian",
  "dance",
  "jazz",
  "oldies",
  "top 40",
  "80s",
  "electronic",
  "mex",
  "mx",
  "entretenimiento",
  "mexico",
  "classic rock",
  "90s",
  "pop music",
  "moi merino",
  "hits",
  "música en español",
  "norteamérica",
  "folk",
  "adult contemporary",
  "country",
  "latinoamérica",
  "local news",
  "community radio",
  "alternative",
  "español",
  "classic hits",
  "house",
  "greek",
  "regional mexican",
  "musica",
  "pop rock",
  "música pop",
  "70s",
  "regional",
  "regional radio",
  "música popular mexicana",
  "música regional",
  "regional mexicana",
  "grupera",
  "indie",
  "musica regional mexicana",
  "mexican music",
  "npr",
  "chillout",
  "soul",
  "information",
  "hiphop",
  "musica regional",
  "traditional mexican music",
  "metal",
  "noticias",
  "ambient",
  "university radio",
  "commercial",
  "musica mexicana",
  "musica tradicional mexicana",
  "news talk",
  "techno",
  "lounge",
  "juvenil",
  "talk & speech",
  "sport",
  "culture",
  "misc",
  "grupero",
  "musica latina",
  "funk",
  "sports",
  "regional music",
  "alternative rock",
  "variety",
  "música del recuerdo",
  "rap",
  "disco",
  "latin pop",
  "entertainment",
  "world music",
  "electro",
  "banda",
  "local music",
  "blues",
  "religion",
  "college radio",
  "rnb",
  "am",
  "local radio",
  "musica latinoamericana",
];

export const tagMappings = {
  rock: [
    "rock",
    "classic rock",
    "pop rock",
    "metal",
    "alternative rock",
    "blues",
  ],
  pop: ["pop", "dance", "pop music", "pop rock", "música pop", "hiphop"],
  news: [
    "news",
    "talk",
    "public radio",
    "local news",
    "community radio",
    "npr",
    "information",
    "news talk",
  ],
  classical: ["classical"],
  latin: [
    "méxico",
    "mex",
    "mx",
    "música en español",
    "español",
    "regional mexican",
    "música pop",
    "música popular mexicana",
    "música regional",
    "regional mexicana",
    "musica regional mexicana",
    "mexican music",
    "traditional mexican music",
    "musica latina",
    "música del recuerdo",
    "latin pop",
    "musica latinoamericana",
  ],
  jazz: ["jazz"],
  "70s": ["70s"],
  "80s": ["80s"],
  "90s": ["90s"],
  "community radio": [
    "local news",
    "community radio",
    "university radio",
    "college radio",
    "local radio",
  ],
  christian: ["christian", "religion"],
  "classic hits": ["oldies", "hits", "classic hits", "classic rock"],
  rnb: ["rnb"],
  electronic: ["electro", "electronic", "techno", "house"],
  disco: ["disco"],
  country: ["country"],
  folk: ["folk"],
  lounge: ["lounge", "ambient"],
};
