export const tagMappings = {
  rock: [
    "rock",
    "classic rock",
    "pop rock",
    "metal",
    "alternative rock",
    "blues",
  ],
  pop: ["pop", "dance", "pop music", "pop rock", "música pop", "hiphop"],
  news: [
    "news",
    "talk",
    "public radio",
    "local news",
    "community radio",
    "npr",
    "information",
    "news talk",
  ],
  classical: ["classical"],
  latin: [
    "méxico",
    "mex",
    "mx",
    "música en español",
    "español",
    "regional mexican",
    "música pop",
    "música popular mexicana",
    "música regional",
    "regional mexicana",
    "musica regional mexicana",
    "mexican music",
    "traditional mexican music",
    "musica latina",
    "música del recuerdo",
    "latin pop",
    "musica latinoamericana",
  ],
  jazz: ["jazz"],
  "70s": ["70s"],
  "80s": ["80s"],
  "90s": ["90s"],
  "community radio": [
    "local news",
    "community radio",
    "university radio",
    "college radio",
    "local radio",
  ],
  'christian' : ['christian', 'religion'], 
  'classic hits' : ['oldies', 'hits', 'classic hits', 'classic rock'], 
  'rnb': ['rnb'], 
  'electronic':['electro', 'electronic', 'techno', 'house', ],
  'disco' : ['disco' ], 
  'country' : ['country'], 
  'folk' : ['folk'],
  'lounge' : ['lounge', 'ambient']
  
};
